modLoader = "javafml"
loaderVersion = "[41,)"
license = "MIT"
issueTrackerURL = "https://github.com/DynamicTreesTeam/DynamicTrees-Quark/issues"

[[mods]]
modId = "dtquark"
version = "${file.jarVersion}"
displayName = "Dynamic Trees for Quark"

updateJSONURL = "https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/Quark.json?raw=true"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-quark"
credits="GroupiX05"
authors="Max Hyper"
description='''
Compatibility Mod between Dynamic trees and Quark
'''

[[dependencies.dtquark]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.dtquark]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.dtquark]]
    modId = "dynamictrees"
    mandatory = true
    versionRange = "[1.3.0-BETA6,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.dtquark]]
    modId = "dynamictreesplus"
    mandatory = false
    versionRange = "[1.2.0-BETA1,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.dtquark]]
    modId = "quark"
    mandatory = true
    versionRange = "[4.0-458,)"
    ordering = "AFTER"
    side = "BOTH"

#This is important to prevent ecologics' plain biome replacement from replacing blossom tree generation
[[dependencies.dtquark]]
    modId="dtecologics"
    mandatory=false
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="BOTH"
